# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sIKDm_iRx4zWS3jU-LAETeDa8PMsgSX0
"""

import streamlit as st
import pandas as pd
import os
from utils import process_batch, get_rwsi_leaderboard

# App Config
st.set_page_config(page_title="🛡️ FraudShield Dashboard", layout="wide")
st.title("🛡️ FraudShield: Real-Time E-Commerce Fraud Detection")
st.markdown("Detect fraudulent transactions in real-time and track seller risk via **RWSI (Risk-Weighted Seller Index)**.")

# File Upload
uploaded_file = st.file_uploader("📂 Upload a transaction CSV file", type=['csv'])

if uploaded_file is not None:
    try:
        df = pd.read_csv(uploaded_file)

        if not {'seller_id', 'amount', 'payment_method', 'device_type', 'location'}.issubset(df.columns):
            st.error("CSV must include: `seller_id`, `amount`, `payment_method`, `device_type`, `location`.")
        else:
            with st.spinner("🔍 Analyzing transactions..."):
                result_df = process_batch(df)

            # Display results
            frauds = result_df[result_df['predicted_fraud'] == 1]
            st.success(f"✅ {len(frauds)} fraudulent transactions detected out of {len(result_df)} total.")

            if not frauds.empty:
                st.subheader("🚨 Fraudulent Transactions")
                st.dataframe(frauds[['transaction_id', 'amount', 'seller_id', 'payment_method']])

                # Save fraud log
                os.makedirs('fraud_logs', exist_ok=True)
                log_path = 'fraud_logs/fraud_batch.csv'
                frauds.to_csv(log_path, mode='a', index=False, header=not os.path.exists(log_path))

            # Show RWSI leaderboard
            rwsi_df = get_rwsi_leaderboard()
            if not rwsi_df.empty:
                st.subheader("📊 Risk-Weighted Seller Index (RWSI)")
                st.markdown("Top sellers with high fraud rates. A higher RWSI means higher risk.")
                st.dataframe(rwsi_df)

            # Optional: Full results
            with st.expander("📜 See full results"):
                st.dataframe(result_df)

            # Download fraud logs
            if os.path.exists('fraud_logs/fraud_batch.csv'):
                with open('fraud_logs/fraud_batch.csv', 'rb') as f:
                    st.download_button("📥 Download Fraud Logs", f, file_name="fraud_log.csv")
    except Exception as e:
        st.error(f"❌ Error processing file: {e}")
else:
    st.info("👆 Upload a CSV file to begin fraud detection.")